# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      #    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: mixed-line-ending
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.3
  hooks:
    - id: markdownlint
    - id: shellcheck
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shfmt
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
    - id: forbid-tabs
      #  - id: insert-license
      #- repo: https://github.com/doublify/pre-commit-clang-format
      #  rev: master
      #  hooks:
      #    - id: clang-format
