---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: "charts/.*"
        args:
          - --allow-multiple-documents
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --pattern
          - '^(?!((fix|feature|refactor)\/[a-zA-Z0-9\-]+)$).*'
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.31.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.2.0
    hooks:
      - id: checkstyle
        args:
          - -c
          - google_checks.xml
        exclude: ".*/src/test/.*"
      - id: cpd
        exclude: ".*/src/test/.*"
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: ".*.(png|jpg|jpeg)$"
      - id: shellcheck
        args:
          - -a
          - -x
          - -P
          - SCRIPTDIR
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shfmt
        args:
          - -l
          - -i
          - "2"
          - -ci
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.22.0
    hooks:
      - id: eslint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: forbid-tabs
        exclude: "^(.*/?Makefile|.*.mk|.*.go)$"
  - repo: https://github.com/doublify/pre-commit-go
    rev: 208a4aaa7f86b44e961eaaea526743b920e187a0
    hooks:
      - id: fmt
      - id: vet
      - id: fix
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        exclude: ".*/templates/.*"
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
        files: docker-compose.*y[a]{0,1}ml$
      - id: docker-compose-check
        files: "^docker/.*yaml$"
      - id: hadolint
        files: ".*.docker$"
        args:
          - --ignore
          - DL3008
          - --ignore
          - DL3013
      - id: hadolint
        files: "Dockerfile.*"
        args:
          - --ignore
          - DL3008
          - --ignore
          - DL3013
  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: docker-clang-format
      - id: cpplint
      - id: docker-cppcheck
        args:
          - --force
